#!/usr/bin/env bash
#
# flash_router.sh — Step-by-step guide for flashing HG531s V1
#
# This script does NOT automate the serial connection — it walks you
# through each step so you can see exactly what is happening.
#
# Usage:
#   chmod +x flash_router.sh
#   ./flash_router.sh
#

echo ""
echo "=========================================="
echo "  HG531s V1 Orange → Tedata Flash Guide"
echo "=========================================="
echo ""
echo "Before starting, make sure:"
echo ""
echo "  1. UART adapter is connected (TX→RX, RX→TX, GND→GND, NO VCC)"
echo "  2. Serial terminal is open at 115200 8N1"
echo "  3. Ethernet cable: PC → any router LAN port"
echo "  4. PC static IP: 192.168.1.2 / 255.255.255.0"
echo "  5. Tedata .bin firmware file is ready"
echo "  6. Browser is open and ready to go to http://192.168.1.1"
echo ""
read -r -p "Ready? Press Enter to continue..."
echo ""
echo "------------------------------------------"
echo "  STEP 1 — Enter the bootloader"
echo "------------------------------------------"
echo ""
echo "  Power-cycle the router."
echo "  Watch the serial terminal for:"
echo ""
echo "    Press 'ESC' to enter BOOT console..."
echo ""
echo "  Press ESC immediately. You should see:"
echo ""
echo "    <RTL867X>"
echo ""
read -r -p "At the <RTL867X> prompt? Press Enter to continue..."
echo ""
echo "------------------------------------------"
echo "  STEP 2 — Apply the patch"
echo "------------------------------------------"
echo ""
echo "  Type this EXACTLY at the <RTL867X> prompt:"
echo ""
echo "    w 0x80d02ec4 0x00000000"
echo ""
echo "  The router will print a new prompt line."
echo ""
read -r -p "Done? Press Enter to continue..."
echo ""
echo "------------------------------------------"
echo "  STEP 3 — Verify the patch"
echo "------------------------------------------"
echo ""
echo "  Type:"
echo ""
echo "    d 0x80d02ec4 8"
echo ""
echo "  You should see:"
echo ""
echo "    0x80D02EC4: 00 00 00 00 ..."
echo ""
echo "  If you see '14 40 00 0B' instead, the patch"
echo "  didn't apply. Go back to Step 2."
echo ""
read -r -p "Verified? Press Enter to continue..."
echo ""
echo "------------------------------------------"
echo "  STEP 4 — Start the web server"
echo "------------------------------------------"
echo ""
echo "  Type:"
echo ""
echo "    web"
echo ""
echo "  The router shows:"
echo ""
echo "    The local IP is 192.168.1.1"
echo "    Listening......"
echo "    Waiting for uploading......"
echo ""
echo "  You have about 60 seconds before it times out."
echo ""
read -r -p "Web server started? Press Enter to continue..."
echo ""
echo "------------------------------------------"
echo "  STEP 5 — Upload firmware"
echo "------------------------------------------"
echo ""
echo "  Go to your browser NOW and open:"
echo ""
echo "    http://192.168.1.1/upload.html"
echo ""
echo "  Select your Tedata .bin file and upload it."
echo ""
echo "  Watch the serial console. A successful flash shows:"
echo ""
echo "    Check DigitalSigned Ok"
echo "    == write config successfully =="
echo "    It is .bin upgrade file!"
echo "    write sys start:bd030000..."
echo "    .....................................................##########"
echo "    RESTART ..."
echo ""
echo "  The dots are progress — this takes 2-3 minutes."
echo "  Do NOT power off during this time."
echo ""
read -r -p "Flash complete and router rebooting? Press Enter to continue..."
echo ""
echo "------------------------------------------"
echo "  STEP 6 — First login"
echo "------------------------------------------"
echo ""
echo "  Wait for the router to finish booting (~60 seconds)."
echo "  Browse to: http://192.168.1.1"
echo ""
echo "  Default credentials:"
echo "    Username: admin"
echo "    Password: admin"
echo ""
echo "  Do a factory reset first to clear old Orange config:"
echo "    Maintenance → Factory Reset"
echo ""
echo "=========================================="
echo "  Done! Router should now run Tedata firmware"
echo "  with Ethernet WAN / FTTH capability."
echo "=========================================="
echo ""
